---

- name: AEW&C A1 - Ground Mission Station Baseline
  hosts: aewc_gms
  become: yes
  roles: 
    - baseline
    - kernel_hardening
    - luks_encryption
    - auditd_logging

- name: AEWC Mission System - Log Server
  hosts: log_servers
  become: yes
  roles:
    - log_server
